function allplates = fcsreadplateseries(datadir, varargin)
%FCSREADPLATESERIES has been replaced by FCSREADPLATES (JW 20120909)
warning(['FCSREADPLATESERIES has been replaced by FCSREADPLATES. '...
    'This function is left to maintain backwards compatibility. '...
    'Please update your code.']);
allplates = fcsreadplates(datadir,varargin);